version: "3.7"
services:
  nginx_idolina:
    image: nginx:1.16-alpine
    container_name: nginx_idolina
    restart: unless-stopped
    ports:
      - "83:80"
    volumes:
      - ./api:/var/www/api
      - ./client:/var/www/client
      - ./docker/nginx:/etc/nginx/conf.d/
      - ./docker/certs:/etc/nginx/certs
    networks:
      - idolina_network
    links:
      - api_idolina
#      - client_idolina

  db_idolina:
    image: mysql:5.7.22
    container_name: db_idolina
    restart: unless-stopped
    tty: true
    ports:
      - "3312:3306"
    environment:
      MYSQL_DATABASE: idolina_app_db
      MYSQL_ROOT_PASSWORD: idolina_app_password
      MYSQL_PASSWORD: idolina_app_password
      MYSQL_USER: idolina_app_user
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./db_data:/var/lib/mysql
      - ./docker/mysql:/etc/mysql/conf.d
    networks:
      - idolina_network

  api_idolina:
    build:
      args:
        user: vlad
        uid: 1000
      context: ./docker
      dockerfile: Dockerfile
    tty: true
    container_name: api_idolina
    restart: unless-stopped
    working_dir: /var/www/api
    volumes:
      - ./api:/var/www/api
    networks:
      - idolina_network
    links:
      - db_idolina

#  client_idolina:
#    image: node:lts-alpine
#    container_name: client_idolina
#    tty: true
#    volumes:
#      - ./client:/client
#    working_dir: /client
#    environment:
#      NODE_ENV: development
#    command: npm run serve
#    networks:
#      - idolina_network

volumes:
  db_data:

networks:
  idolina_network:
    driver: bridge
